### ISSUE TITLE
Formatting when comments are present change query layout

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#102]
Hi,

1. Open `sqlite-gui 1.71` with the bookstore database.
2. Type test
3. Press enter for a blank line
4. Press enter for a blank line
5. Type simple query: `select * from books`
8. Select the `test` text
9. Press `ctrl` + `/`
10. Notice test is now commented out
11. Select all text
12. Press `ctrl` + `t` to format the text
13. Notice your select statement is bunched up with the test text.

```
/*test
*/ select * 
  from books 
```

I would expect commented out sections not to be included in the formatting of a query.

**Comment by little-brother** [comment]
Finally I got to this bug.

After `Ctrl + /` what do ypu have? There are two possibilities:
1. If you select the entire row
```
/*test
*/
select * from books 
```
2. If you select only `test` without trailed `\r\n`
```
/*test*/

select * from books 
```

In first case the formatter saves a raw comment. And therefore it will be expected behaviour.
In second case: this is a bug with commenting.

P.S. Also I found that an editor requires to update highlighting after formatting.

**Comment by jungle-boogie** [comment]
Do you need anything additional for this?

> Also I found that an editor requires to update highlighting after formatting.

Yes, that's something else I've noticed. Thanks for taking a look at that.

**Comment by little-brother** [comment]
> Do you need anything additional for this?

Yes. 

> After Ctrl + / what do ypu have?

**Comment by jungle-boogie** [comment]
After selecting `text` and pressing ctrl + /, I see:

```
/*test*/
```

**Comment by little-brother** [comment]
Thanks. So this is a not a bug and therefore a new version may be released :)
