### ISSUE TITLE
fixed viruses

### ISSUE THREAD

**Issue by Evonic4** [little-brother/sqlite-gui#118]
https://www.virustotal.com fixed viruses

AhnLab-V3

Malware/Win32.RL_Generic.R362193
Cylance

Unsafe
MaxSecure

Trojan.Malware.114175056.susgen
McAfee

GenericRXAA-AA!D56CCF32FEAC
Rising

Trojan.Injector!8.C4 (CLOUD)
Acronis (Static ML)

Undetected

**Comment by little-brother** [comment]
I suppose that issue related to [know problem](https://github.com/little-brother/sqlite-gui/wiki#virus-warnings).
If you checked an entire archive then `exec`-extension can produce many warnings because it call `CreateProcess`-function that make antivirus much more suspisios.

You can drop this extension if you don't plan to use it.
