### ISSUE TITLE
Incompatible with Chinese input method

### ISSUE THREAD

**Issue by denonleee** [little-brother/sqlite-gui#141]
Hi,
When I use the native Chinese input method of Windows 11 x64, I cannot complete the correct input.
For example, I want to enter 'yanse' in Chinese mode, 'se' activates autocompletion.

![image](https://user-images.githubusercontent.com/127704105/224588090-63ef6a21-55ac-4b29-ae01-e049e35e904e.png)
![image](https://user-images.githubusercontent.com/127704105/224588137-c365eac6-3289-43de-b417-720a3da79bec.png)

Thanks!

**Comment by little-brother** [comment]
Unfortunally I can't check this error because I don't have Win11 and Chinese keyboard :(

The autocomplete checks that you are not inside quotted string and suggests options. So the issue behaviour is predicted.
What about some key shortcut to quick turn on/off the autocomplete e.g. `F6`?
Also you can try to switch an autocomplete commiting to `TAB` (instead `Enter`) in Settings or turn it off by `.set use-autocomplete 0` in the terminal.

**Comment by denonleee** [comment]
I checked again.This is not an error. 

The reason is that the Chinese input method（native of Windows 11） will use single quotation marks to segment words automatically, resulting in the activation of automatic completion. 

The solution is to turn off automatic completion or use the third party Chinese input method.
