### ISSUE TITLE
Numeric columns alignment

### ISSUE THREAD

**Issue by sergioferrari** [little-brother/sqlite-gui#145]
Hi Little Brother, 
I am using **sqlite-gui** to work on a sqlite3 database and I notice that several columns, with numerical values of the same type (INTEGER or REAL), are aligned sometimes left and sometimes right.
I attach two screenshots.
In my opinion the columns with numeric values (both INTEGER and REAL) should all be aligned to the right, while the columns containing TEXT should be aligned to the left.
I take this opportunity to congratulate you for your program, really well done and with many interesting features.
<img width="403" alt="integers" src="https://github.com/little-brother/sqlite-gui/assets/49869701/64c86ddc-2da9-484e-a83d-0a9158a60145">
<img width="386" alt="reals" src="https://github.com/little-brother/sqlite-gui/assets/49869701/429161eb-db18-4698-9c04-8c4f7435257f">

**Comment by little-brother** [comment]
As I can see you encountered with an incorrect aligment in a view. How is this column calculated?
Do you have the same issue in a table? What has datatype column in the `source` table?

The alignment is defined by a column type returning SQLite. I suppose that sometime (e.g. in your cases) SQLite couldn't do it correctly because the column uses mixed types and SQLite returns `NULL`.

**Comment by little-brother** [comment]
Fixed.
