### ISSUE TITLE
credentials?

### ISSUE THREAD

**Issue by ghost** [little-brother/sqlite-gui#158]

**Comment by little-brother** [comment]
As you mention, SQLite doesn't support credentials itself because it's a simple file. MySQL and other RDBMS are services. And it's a common practice to use credentials for services because multiple users are using a service at the same time. Generally SQLite is used by one user in monopoly mode.   

There is no sense for me to make protection on a file level, Even Linux apps don't do it. You should use `sudo` (`Run as administrator` on Windows) to open files that the current user does not have access to. I don't know any app which change privileges for a file before it will be opening.

To protect data you can encrypt a file via `Database > Set encryption` and you will see a request dialog with cipher params on the next opening.  Nobody reads the encrypted database without ecryption algorythm/password/another params. Of course, you can't split read and read-write privileges by ecnryption. But you can disable the `write` permission for a file on OS level.

I assume you want to solve some problem of your own with credentials. But it looks like you are thinking in the wrong direction. Could you explain what kind of problem you want to solve? You can send me a letter on lb-im@ya.ru if you don't want do describe it publicly.
