### ISSUE TITLE
Save result as table is slow

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#65]
Hi,

I like the idea of saving the results to a table after you run a query on it. 

It seems that creating the table can take some time, causing squlite-gui to not respond for a few seconds. When I first tested it, I created a table with ~1700 records and I thought the app was going to crash, because it was unresponsive for a couple minutes. The app did not crash and the table was successfully created, but it was slower than I imagined.

Have you noticed the same pause non-responsiveness when creating a table as well?

thanks!

**Comment by little-brother** [comment]
Thanks, I didn't test this feature for thousands rows (only for hundreds). 
~~Yes, the export is slow because builded by data from a grid control.
If an query produced more than `row-limit` (10K by default) then the export fetchs the data from the database directly (and this is much faster).~~
I forgot to wrap all insertions in one transaction. It's a bug.

**Comment by jungle-boogie** [comment]
I tested it with a few hundred results and it also paused as well. The pause wasn't as long as with 1700 records, though.

**Comment by little-brother** [comment]
Without wrapping each result row is inserted as one separate transaction. SQLite is relatively slow ~10-100 transaction/s because SQLite waits IO-system (SSD or HDD) confirmation (can be turn off by `pragma synchronous = off`). So 1700 rows generated 1700 transactions instead one.
