### ISSUE TITLE
Display temporary tables

### ISSUE THREAD

**Issue by ddumitriu** [little-brother/sqlite-gui#99]
Add a node for temporary tables in the LHS tree view similarly to the regular tables - you can use the temp.sqlite_master metatable.

**Comment by little-brother** [comment]
I don't see a big profit to have such feature because there is a one nuance.
sqlite-gui uses separate connections per a tab (it allows to run several queries at the same time). 
But an each connection has own `TEMP`-schema and therefore the nav-tree (TEMP-node) should be rebuilded on each tab switch. It's not very good.

But I'll add `TEMP`-names to auto-complete.

**Comment by ddumitriu** [comment]
It's up to you to ponder the disadvantages; maybe autocomplete would suffice - you might add it and run some tests. But it is certainly unfortunate not to get any feedback on existing temporary tables, especially when those had been by definition created by the same user (or tab owner, technically).

**Comment by little-brother** [comment]
Most of IDE (except DB4S) don't have this feature. So I don't this it's a very important.
Nevertheless I already have a point "Schema selector" on a tree top in my ToDo list. That can be usefull not only for `temp`-schema but for any attached databases. But there are many another points and I should get desire to make it.

**Comment by little-brother** [comment]
Done.
